{% set version = "0.27.3" %}

package:
  name: referencing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/referencing/referencing-{{ version }}.tar.gz
  sha256: 1bcd8d9e76d584b132af4d0318f4de686c11873d2636f8d72d8f00280fb5bd92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.8
  run:
    - attrs >=22.2.0
    - python >=3.8
    - rpds-py >=0.7.0

test:
  imports:
    - referencing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-jsonschema/referencing
  summary: JSON Referencing + Python
  license: MIT
  license_file: COPYING
  doc_url: https://referencing.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
