{% set name = "referencing" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44aefc3142c5b842538163acb373e24cce6632bd54bdb01b21ad5863489f50d8

build:
  number: 0
  skip: true  # [py<310]
  script_env:
    - REFERENCING_SUITE=./suite
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python
  run:
    - attrs >=22.2.0
    - python
    - rpds-py >=0.7.0
    - typing_extensions >=4.4.0  # [py<313]

test:
  source_files:
    - suite
  imports:
    - referencing
    - referencing.exceptions
    - referencing.jsonschema
    - referencing.retrieval
    - referencing.typing
  commands:
    - pip check
    - pytest -vv --pyargs referencing --cov=referencing --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=99
  requires:
    - pip
    - pytest-cov
    - pytest-subtests

about:
  home: https://github.com/python-jsonschema/referencing
  summary: JSON Referencing + Python
  description: |
    An implementation-agnostic implementation of JSON reference resolution.
  license: MIT
  license_family: MIT
  license_file: COPYING
  doc_url: https://referencing.readthedocs.io
  dev_url: https://github.com/python-jsonschema/referencing

extra:
  recipe-maintainers:
    - bollwyvl
