{% set version = "0.30.1" %}

package:
  name: referencing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/referencing/referencing-{{ version }}.tar.gz
  sha256: 9370c77ceefd39510d70948bbe7375ce2d0125b9c11fd380671d4de959a8e3ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.8
  run:
    - attrs >=22.2.0
    - python >=3.8
    - rpds-py >=0.7.0

test:
  imports:
    - referencing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-jsonschema/referencing
  summary: JSON Referencing + Python
  license: MIT
  license_file: COPYING
  doc_url: https://referencing.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
